### PR TITLE
List stack resources function fixed

### PR DESCRIPTION
**Pull request by Enase**
Fix for https://github.com/funkybob/serverless-s3-deploy/issues/58

### CODE REVIEW

**Comment by ynx** [comment]
Can confirm this code change fixed issue in my case.

**Comment by ghost** [comment]
Any news on a release for this? 🙌

**Comment by Bloodday** [comment]
This fix works, the plugin works again with this change.

**Comment by her079** [comment]
When will it be released? Thanks!

**Comment by Bloodday** [comment]
@her079 > When will it be released? Thanks!

I cheked the repository history, and it don't have much activity, so i don't expect this to be solved in the near future, I modified the index.js file directly in my node_modules folder to be able to continue working

**Comment by her079** [comment]
> @her079 > When will it be released? Thanks!
> 
> I cheked the repository history, and it don't have much activity, so i don't expect this to be solved in the near future, I modified the index.js file directly in my node_modules folder to be able to continue working

Thanks! In my case I prefer to to decrease the version from serverless to 2.22.0. :)

**Comment by funkybob** [comment]
Thanks for the fix!

Sorry for the slow response; I don't use serverless much any more, so don't often look at this.

**Comment by funkybob** [comment]
New version has been published.

**Pull request merged**
